### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by easiwriter** [AndreaMiotto/PartialSheet#10]
I have tried this in my app by replacing different working instances of .sheet with .partialSheet and none of them has worked. The results have either been a blank sheet or corruption of the presenting view. Nice idea but I suspect it needs broader testing.

**Comment by WiildchiilD** [comment]
Nope, it’s working normally. But maybe you need to provide us with some code so you can get help.

**Comment by easiwriter** [comment]
Here is some code and some screenshots. I thought that .partialSheet was intended to be a drop in - that's what the readMe suggests.

Shot 1 shows the sheet that is already working. Shot 4 shows the navBar with the button used to activate it (the wand icon). Shot 2 shows the navBar with .partialSheet. Shot 3 shows it after making the view the first responder - the button has vanished, so you can't display the sheet.

Here is the code for the button using sheet.

            Button(action: ({
                if self.textView.isFirstResponder {
                    self.$fontSize.wrappedValue = Int(self.styleModel.getStyleChanges().fontSize)
                    self.showModal.toggle()
                }
                else {
                    self.showAlert.toggle()
                }
            })) {
                Image(systemName: "wand.and.stars")
                    .foregroundColor(Color("WriteNowColor"))
                    .imageScale(.large)
            }.padding()
            .sheet(isPresented: $showModal) {
                StyleEditor(styleModel: self.styleModel,
                            allFonts: self.allFonts,
                            textView: self.$textView,
                            fontSize: self.$fontSize,
                            version: self.version)
            }.alert(isPresented: self.$showAlert, content: { self.alert })
            
The code using partialSheet is the same with .sheet(isPresented: $showModal) changed to .partialSheet(presented: $showModal)

[shot 1.pdf](https://github.com/AndreaMiotto/PartialSheet/files/4381490/shot.1.pdf)
[shot 2.pdf](https://github.com/AndreaMiotto/PartialSheet/files/4381507/shot.2.pdf)
[shot 3.pdf](https://github.com/AndreaMiotto/PartialSheet/files/4381511/shot.3.pdf)
[shot 4.pdf](https://github.com/AndreaMiotto/PartialSheet/files/4381561/shot.4.pdf)

**Comment by easiwriter** [comment]
I think the problem might be due to scroll views - my sheet is embedded in one.
