### ISSUE TITLE
When  partialSheetManager.showPartialSheet()  in a fullScreenCover view , the  PartialSheet view  obscured by fullScreenCover 

### ISSUE THREAD

**Issue by jiangdi0924** [AndreaMiotto/PartialSheet#104]
Tks for created this pkg,it is very useful. But when  use  partialSheetManager.showPartialSheet()  in a fullScreenCover view , the  PartialSheet view  obscured by fullScreenCover .
How I can solve it?

**Comment by WelkinDev** [comment]
I had the same problem,How did you solve it？

**Comment by jiangdi0924** [comment]
> I had the same problem,How did you solve it？

no,  just change to another solution
