### ISSUE TITLE
Is it possible to display PartialSheet on top of UITabBar outside of UiHostingViewController?

### ISSUE THREAD

**Issue by kschins** [AndreaMiotto/PartialSheet#105]
The root of our app is a UITabBarController which is done in UIKit. We have a UIHostingViewController in one of the tabs yet the PartialSheet shows above the tab bar. This might be a SwiftUI bug and what you can access via the view hierarchy, or do we need to make the root view of the application the UIHostingViewController to achieve the desired results?

**Comment by AndreaMiotto** [comment]
Sorry for the delay, let me know id you still have this problem, and if yes, can you explain it a little bit better?
In the meanwhile I close the issue.
