### ISSUE TITLE
Swiftui lifecycle: No scene or appdelegate

### ISSUE THREAD

**Issue by trevordevelops** [AndreaMiotto/PartialSheet#108]
Hey Im trying to figure out how to use this package with no app or scene delegate. I selected SwftUI for my lifecycle when creating my project and say I cannot go back and create a new project with UI Kit appdelegate. How could I go about installing the partial sheet manager? I am fairly new to swiftui so I would really appreciate any help, i couldnt find any real answes on stack. If anyone has any ideas on how to make this work with swiftui life cycle I feel like there might be others that could benefit from an answer as well, thank you!

Here is my SwiftUI lifecycle:

    var body: some Scene {
        WindowGroup {
            ContentView(coin: DeveloperPreview.instance.coin)
                .environmentObject(vm)
        }
    }

**Comment by AndreaMiotto** [comment]
Hello @trevordevelops this issue is not related to the package itself.
Also, you question it's not totally clear to me.
Check the example project in the repository, it will shows you how to work with the partial sheet

**Comment by trevordevelops** [comment]
It is related to the package in the form of installation. With more and more developers using SwiftUI lifecycle rather than app/scene delegate I think its important to leave a thread open for devs to come together and discuss a solution to this problem. There is simply no way to use the partial sheet with no app/scene delegate. I understand this is all complimentary code and I expect no direct answer from you, but rather the community. The example code all uses installation with app/scene delegate.
