### ISSUE TITLE
Cannot find a way to disable drag and tap gesture

### ISSUE THREAD

**Issue by hs-echkayben** [AndreaMiotto/PartialSheet#109]
Trying to find a way to make a user unable to dismiss the sheet unless a certain textfield is filled, but I can't seem to find any controls available to disable the sheet dismissal. Any way to do this behaviour at the moment?

**Comment by hs-echkayben** [comment]
Although I was able to disable these gestures when I copied, pasted, and modified the code but since TextField doesn't seem functional on iPhone I had to include PartialSheet as an SPM, and therefore I lost my ability to remove unwanted gestures

**Comment by AndreaMiotto** [comment]
I will try to introduce this feature in the version 3 of the project
