### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by mengdun** [AndreaMiotto/PartialSheet#11]
It there any way we can change the entire background color of the sheet, looks like it is always in white color. Would like to use it in dark mode. 
Thank you so much!

**Comment by AndreaMiotto** [comment]
Yes, you have the backgroundColor argument:

```Swift
public func partialSheet<SheetContent: View>(
		presented: Binding<Bool>,
        backgroundColor: Color = Color(UIColor.tertiarySystemBackground),
        handlerBarColor: Color = Color(UIColor.systemGray2),
		enableCover: Bool = true,
		coverColor: Color = Color.black.opacity(0.4),
		view: @escaping () -> SheetContent ) 
```

Anyway I've just pushed a new version with a default system color for dark mode.

**Comment by skywalkerlw** [comment]
how can we change background color if we present sheet via `self.partialSheetManager.showPartialSheet`
