### ISSUE TITLE
Stepper doesn't detect the tap on PartialSheet master branch.

### ISSUE THREAD

**Issue by cikpis** [AndreaMiotto/PartialSheet#111]
Stepper that is inside the PartialSheet does not detect the tap plus or minus on PartialSheet master branch.

In tag version 2.1.11 works correctly.

Any clue why?

**Comment by AndreaMiotto** [comment]
fixed with 2.1.12

**Comment by cikpis** [comment]
I could find any 2.1.12. Are you planning to release it soon?

**Comment by cikpis** [comment]
Never mind, found it. Does it contains also all the changes that are on master branch?
