### ISSUE TITLE
When partialSheetManager.showPartialSheet() in a fullScreenCover view, PartialSheet can not display

### ISSUE THREAD

**Issue by WelkinDev** [AndreaMiotto/PartialSheet#113]
### Code
1. SceneDelegate Part

`func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        let sheetManager: PartialSheetManager = PartialSheetManager()
        let contentView = TabbarView()
            .environmentObject(sheetManager)
        if let windowScene = scene as? UIWindowScene {
            let window = UIWindow(windowScene: windowScene)
            window.rootViewController = UIHostingController(
                rootView: contentView
            )
            self.window = window
            window.makeKeyAndVisible()
        }
    }`

2. TabbarView Part

`struct TabbarView: View {
    var body: some View {
        TabView {
            FirstView()
            .tabItem {
                Image(systemName: "list.dash")
                Text("First")
            }
            Text("Content 2")
            .tabItem {
                Image(systemName: "list.dash")
                Text("Second")
            }
        }
        .addPartialSheet()
    }
}`

3. First TabItem 

`struct FirstView: View {
    @State var showFullScreenCover = false
    var body: some View {
        VStack {
            Button(action: {
                showFullScreenCover.toggle()
            }, label: {
                Text("show Full Screen View")
            })
        }
        .fullScreenCover(isPresented: $showFullScreenCover, content: {
            FullScreenView()
        })
    }
}`

4. Try to Show ParticalSheet

`struct FullScreenView: View {
    @EnvironmentObject var partialSheet : PartialSheetManager
    @State private var groupNames: [String] = ["1","2","3","4","5"]
    @State private var selectedGroupIndex = 0
    var body: some View {
        NavigationView {
            VStack(alignment: .center) {
                Spacer()
                    Button(action: {
                        self.partialSheet.showPartialSheet({
                            print("dismissed")
                        }) {
                            Picker(selection: $selectedGroupIndex, label: Text("Picker"), content: {
                                ForEach(0..<groupNames.count) { idx in
                                    Text(groupNames[idx])
                                }
                            })
                        }
                    }, label: {
                        Text("Show Partial Sheet")
                    })
                Spacer()
            }
            .navigationBarTitle("Partial Sheet")
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}`

### View Hierarchy

![image](https://user-images.githubusercontent.com/38003364/122915104-f473a080-d38d-11eb-9d2c-885b3ede1114.png)

**Comment by WelkinDev** [comment]
Call .addPartialSheet() method at fullScreenCover View can resolve this problem

**Comment by WelkinDev** [comment]
Em... When dismiss this fullScreenCover View, app will crash.
How can I resolve it?

**Comment by jiangdi0924** [comment]
@WelkinDev  same issue..  , have you fixed it?

**Comment by WelkinDev** [comment]
> @WelkinDev same issue.. , have you fixed it?

No. I use system method instead. :(

**Comment by jiangdi0924** [comment]
> > @WelkinDev same issue.. , have you fixed it?
> 
> No. I use system method instead. :(

me too
