### ISSUE TITLE
Multiple snap points (like apple maps)

### ISSUE THREAD

**Issue by bryan1anderson** [AndreaMiotto/PartialSheet#115]
This library looks promising with its ease of use, but its missing something I've found in a lot of UIKit based alternatives. Unfortunately, I am not able to use the UIKit alternatives right now and so I'm making a feature request.

I would like to add the ability to customize the sheet to expand to multiple points. 
Closed: swiped off screen all the way down
Minimized: like in apple maps where you drag the drawer down to the bottom but you can still see the search bar.
Medium: drawer slides and snaps to a specified point
Open: the way it currently works. All the way open!

**Comment by AndreaMiotto** [comment]
The Partial Sheet adapt his size according to his content..
You can achieve to have different anchor points modifying the height of is content
