### ISSUE TITLE
Mixed UIKit & SwiftUI?

### ISSUE THREAD

**Issue by JetForMe** [AndreaMiotto/PartialSheet#117]
Does this work in a mixed environment? We have UIKit at the root of our hierarchy, and some views within are SwiftUI. I don't have a SwiftUI SceneDelegate. Will this still work, so long as I add the manager to the environment?

**Comment by 1337domz** [comment]
Yeh you can use this with a UIKit based app. In my App I create the PartialSheetManager in my AppDelegate and pass it through the environment

**Comment by JetForMe** [comment]
Can I create multiple `PartialSheetManager`s (e.g. one for each main tab of my app)?

**Comment by AndreaMiotto** [comment]
Yes you can
