### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by Hustenbonbon** [AndreaMiotto/PartialSheet#12]
Hey, it would be totally awesome if you provide a license, otherwise it is illegal for others to use your code. 

The license you choose is for sure up to you, but I would suggest to make it as easy as possible for people to use your code, use the [Unlicense](https://tldrlegal.com/license/unlicense).
Otherwise, [MIT is a popular choice](https://choosealicense.com/).

Great swiftui element you developed there!

**Comment by AndreaMiotto** [comment]
You are right, done it

**Comment by Hustenbonbon** [comment]
Thanks for that super quick response!
