### ISSUE TITLE
Cannot use PartialSheet via SPM on Xcode 13 b3/b4

### ISSUE THREAD

**Issue by 1337domz** [AndreaMiotto/PartialSheet#120]
The way SPM works has changed in these versions of Xcode, and you will get the following error:

> 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

Here are a few links about the change/issue:

https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333
https://bugs.swift.org/browse/SR-14944

Other SDKs/packages have implemented the needed declarations, such as Firebase:

https://github.com/firebase/firebase-ios-sdk/pull/8405/files

**Comment by iNishantKhare** [comment]
I am also getting same error, is there any workaround until this is fixed?

**Comment by 1337domz** [comment]
You could use my fork until the changes get merged in:

https://github.com/1337domz/PartialSheet

The other option is to temporarily remove the package and add the source files directly to your project.

**Comment by JetForMe** [comment]
Just ran into this myself. Other packages have marked their methods that uses these as unavailable to extensions as well.
