### ISSUE TITLE
Bound preference SheetPreferenceKey tried to update multiple times per frame.

### ISSUE THREAD

**Issue by sathamkhussain** [AndreaMiotto/PartialSheet#126]
Often getting this message in my console while showing the partial sheet. 

Bound preference SheetPreferenceKey tried to update multiple times per frame.

Will it be an issue while publishing the app?

**Comment by AndreaMiotto** [comment]
Check the v2.1.13

**Comment by majis15** [comment]
I still get this messages. (iOS 15, v 2.1.14)

**Comment by sathamkhussain** [comment]
Yes. Even I am also getting the same.

**Comment by majis15** [comment]
@AndreaMiotto are there any solutions?

**Comment by sathamkhussain** [comment]
But I don't think it's affecting the app. App is working fine.
