### ISSUE TITLE
Thread 1: Fatal error: No ObservableObject of type PartialSheetManager found. A View.environmentObject(_:) for PartialSheetManager may be missing as an ancestor of this view.

### ISSUE THREAD

**Issue by Anooppakki** [AndreaMiotto/PartialSheet#127]
added EnvironmentObject, observableobjects in both the partisheetView and my mainView and still get this error. 

Any help would be appreciated! 

running Xcode 12.5.1

**Comment by AndreaMiotto** [comment]
can you send me some code?

**Comment by AC40** [comment]
Hey, I ran into the same issue. Could you tell me if you found a solution to this bug and if so what it was?
Thanks in advance!

**Comment by AC40** [comment]
Hey, I ran into the same issue. Could you tell me if you found a solution to this bug and if so what it was?
Thanks in advance!

**Comment by danielerne** [comment]
We experience the same problem. Is this repo still active. Last update was on September 21 :(
