### ISSUE TITLE
Enable Adding Library via Cocoapods

### ISSUE THREAD

**Issue by adrianhartanto004** [AndreaMiotto/PartialSheet#131]
Hi there the library is great and love it so far!

I think It would be awesome if this library can be added via cocoapods.

Thank you so much in advance!

**Comment by lozzoc** [comment]
can you explain why your project does not allow the addition of swift packages?

**Comment by AndreaMiotto** [comment]
I don't have any plan to add Cocoapod or Cartage support, I wouldn't have enough time to maintain it. If I will have more collaborators I may will do it. Also feel free to open a PR
