### ISSUE TITLE
Animation issue upon calling .showPartialSheet()

### ISSUE THREAD

**Issue by PocketDaniel** [AndreaMiotto/PartialSheet#134]
I am having an issue with animation upon calling `partialSheetManager.showPartialSheet(...)` - it appears that text is animated faster than rest of the view:

https://user-images.githubusercontent.com/29543138/144748171-1187796b-5646-4d1e-a981-7214597a21cc.mov

And if I remove `.font` modificator from text in `AppearanceSelectionRow` (line 27), then I am getting much weirder behaviour, where 2 out of 3 texts are animated correctly and 3rd one is faster than the rest of the view:

https://user-images.githubusercontent.com/29543138/144748332-edbac10d-0b0e-40cd-ad65-e400af2ac0b4.mov

I am not sure why it is happening and not sure if it is a package issue or my code. This behaviour is reproducible not only in simulator, but on a real device too - iPhone 13 Pro with iOS 15.1. Do you have any ideas why it is happening and how can I fix that?

P.S. Made a test project with a code that have this bug - https://github.com/PocketDaniel/PartialSheetIssue

**Comment by AndreaMiotto** [comment]
Check version 3.0 and if you still have the issue, feel free to reopen the issue
