### ISSUE TITLE
Keyboard makes the view all the way up

### ISSUE THREAD

**Issue by cikpis** [AndreaMiotto/PartialSheet#135]
Hi @AndreaMiotto,

as mentioned already [here](https://github.com/AndreaMiotto/PartialSheet/issues/53) in my [comment](https://github.com/AndreaMiotto/PartialSheet/issues/53#issuecomment-983408582), this bug seems not fixed. 

Looking forward to hearing from you, cheers!

**Comment by AndreaMiotto** [comment]
Can you provide a working case for this problem?
With the version 3.0 of Partial Sheet
