### ISSUE TITLE
List doesn't fit and not responsive in presented sheet

### ISSUE THREAD

**Issue by mylogon341** [AndreaMiotto/PartialSheet#136]
This might be a user error or documented 'feature' but I can't seem to have a responsive table/ list in the presented sheet.

Expectation
<img width="498" alt="Screenshot 2021-12-31 at 3 51 22 pm" src="https://user-images.githubusercontent.com/5493303/147831365-8e5679ea-a4c2-43b7-ab6e-7cfcc55f6eaa.png">

vs reality
![Simulator Screen Shot - iPod touch (7th generation) - 2021-12-31 at 15 51 24](https://user-images.githubusercontent.com/5493303/147831559-58b3c057-568a-42d2-9f85-84d9bc97e557.png) 

I created this screen with the following code
```swift
import SwiftUI
import PartialSheet

struct LocationSearchView: View {
  
  @ObservedObject var viewModel = LocationSearchViewModel()
  
    var body: some View {
      VStack(alignment: .leading) {
        
        Text(AAString.Map.Search.title)
          .font(.headline)
        
        HStack(spacing: 5) {
          Image(systemName: "magnifyingglass")
          TextField(AAString.Map.Search.Textfield.placeholder,
                    text: $viewModel.searchTerm)
        }
        .padding(4)
        .overlay(
          RoundedRectangle(cornerRadius: 4)
            .strokeBorder()
          )
        
        List($viewModel.searchLocations) { location in
          let item = location.searchLocation.wrappedValue
          let placemark = item.placemark
          
          LocationSearchResultRow(title: placemark.name ?? "",
                                  subtitle: placemark.title ?? "")
            .onTapGesture {
              self.viewModel.tappedItem(item)
            }
        }
        .listStyle(.plain)
        .overlay(
          RoundedRectangle(cornerRadius: 4)
            .strokeBorder()
        )
      }
      .padding()
    }
}

struct LocationSearchView_Previews: PreviewProvider {
    static var previews: some View {
      let model = LocationSearchViewModel()
      defer { model.searchTerm = "McDonald's" }
      return LocationSearchView(viewModel: model)
    }
}
```
The `searchLocation` is a `[MKMapItem]` but could probably just be anything in this case.

Anyway, in the preview screen, it's fully responsive and fits the page. However when running in simulator, the table is off screen and doesn't scroll at all, which is inconvenient. 
Are there any considerations or workarounds that I should be aware of for this?
Thanks

**Comment by mylogon341** [comment]
It's probably worth noting that the `.onTapGesture` does work.

**Comment by mylogon341** [comment]
I was able to work around this by nesting a `VStack` inside a `Scrollview` like so 
```swift
ScrollView(.vertical) {
          VStack(alignment: .leading) {
            ForEach($viewModel.searchLocations) { location in
```
and then tweaking the row to look more like a table row. I then also set the frame of the scrollview to 
```swift
.frame(maxWidth: .infinity, maxHeight: 250) 
```
so it doesn't go off screen.e

**Comment by AndreaMiotto** [comment]
Check version 3.0
