### ISSUE TITLE
onDismiss Closure

### ISSUE THREAD

**Issue by jhparshall** [AndreaMiotto/PartialSheet#14]
This is great work. Thanks for your effort!

I would like execute some code when the user dismisses the sheet. Have you considered adding an onDismiss: closure?

Thank you.

**Comment by AndreaMiotto** [comment]
Good idea, I will add it in the next release. Stay tuned!

**Comment by AndreaMiotto** [comment]
added the onDismissn() on version 1.0.3

**Comment by jhparshall** [comment]
Works well. Thanks!
