### ISSUE TITLE
Scrollable Content Appears As Middle Sheet

### ISSUE THREAD

**Issue by Twigz** [AndreaMiotto/PartialSheet#141]
## Description
The `.scrollView` type for the partial sheet presentation modifier seems to cause the sheet to present in the middle of the screen, rather than be attached to the bottom. Tried it out in the demo app and it seemed to have the same behavior.

## Environment
Xcode 13.2.1, iOS 15.2 Simulator (iPod Touch, iPhone 13)

## Screenshots
![Simulator Screen Shot - iPod touch (7th generation) - 2022-03-03 at 16 52 00](https://user-images.githubusercontent.com/1043416/156659077-691c9f0c-8402-4a63-9cbc-452a1cdb878e.png)
![Simulator Screen Shot - iPod touch (7th generation) - 2022-03-03 at 16 51 55](https://user-images.githubusercontent.com/1043416/156659078-ac651f01-2b35-487d-a979-57aa0b38c2a8.png)

**Comment by AndreaMiotto** [comment]
mmh on my simulator does not happen, I will look into it right now
