### ISSUE TITLE
Keyboard doesn't work with dynamic height

### ISSUE THREAD

**Issue by ygee07** [AndreaMiotto/PartialSheet#151]
Whenever the keyboard is displayed inside a partial sheet,
it stops following the supposed dynamic height.

Keyboard Hidden
<img src="https://user-images.githubusercontent.com/2621883/169769220-e2b68070-f43f-42f8-9a85-3bb7e3bb0b7d.png" width="200" />
Keyboard Shown
<img src="https://user-images.githubusercontent.com/2621883/169769236-d3d61493-c1e6-4aab-adc5-ea7d347db986.png" width="200" />

I've also recreated this in another repo so you check:
https://github.com/greyder/PartialSheetSample

Also not working with `type: .scrollView`

**Comment by benjaminleonard** [comment]
I have the same issue. Did you find a workaround?

**Comment by greyder** [comment]
> I have the same issue. Did you find a workaround?

not yet  😕

**Comment by adrianhartanto004** [comment]
I've created a bugfix for this issue. PR has been created here: https://github.com/AndreaMiotto/PartialSheet/pull/168
