### ISSUE TITLE
The `DragGesture.onEnded(_:)` not be called up.

### ISSUE THREAD

**Issue by LimChihi** [AndreaMiotto/PartialSheet#160]
### Description

If user used more than one finger, The `DragGesture.onEnded(_:)` will not be called up.

### Environment

Xcode Version 14.0 beta (14A5228q) 
iPhone 12 Pro Max 15.5 (19F77)

### Screen recording

https://user-images.githubusercontent.com/18307084/177292288-3f8d3ee9-9ea0-447c-86cd-80b5d0a44f78.MOV

**Comment by AndreaMiotto** [comment]
Try now after the merge of the PR.
