### ISSUE TITLE
Not playing animations when closing per drag

### ISSUE THREAD

**Issue by Hustenbonbon** [AndreaMiotto/PartialSheet#17]
Hey, nice work!
I noticed that the animation is only played when closing per tap on the background, not on drag-closing. 
[Here is a PR fixing it](https://github.com/AndreaMiotto/PartialSheet/pull/16) :-)

Or is this intended? Then I'll just use my fork

**Comment by AndreaMiotto** [comment]
There is a very fast animation, I didn't want to delay too much the user. 
Usually when you close a modal with the drag gesture, you want it close as soon as possible and don't wait for a slower animation.

I saw you PR and I've commented. Feel free to follow up there.

**Comment by Hustenbonbon** [comment]
Ah yes, sorry I was very inprecise: 
I am talking about animating the cover, that it fades out instead of disappears. Saw the side effects of my PR, will think of another solution

**Comment by AndreaMiotto** [comment]
ok, reopened the issue, if I have time today I will look into it.
