### ISSUE TITLE
Crash on tap to show the Partial sheet

### ISSUE THREAD

**Issue by Taimoor20** [AndreaMiotto/PartialSheet#176]
I am tapping my button to show the Partial Sheet view but the app got crashed saying 

> Thread 1: Fatal error: No ObservableObject of type PSManager found. A View.environmentObject(_:) for PSManager may be missing as an ancestor of this view.

in library's **PSManagerWrapper** class

This is the link of the image: https://ibb.co/B6QXCMZ

**Comment by sergei-mikhailovskii-idf** [comment]
Hello! it seems that u missed this lines in your code, innit?

/**
 The Partial Sheet Manager helps to handle the Partial Sheet when there are many view layers.
 Make sure to pass an instance of this manager as an **environmentObject** to your root view:
 ```
 let sheetManager: PSManager = PSManager()
 contentView.environmentObject(sheetManager)
 ```
 */
