### ISSUE TITLE
The partial sheet is not in the right position if putting it inside a List.

### ISSUE THREAD

**Issue by phuhuynh2411** [AndreaMiotto/PartialSheet#19]
I put the partialSheet inside a List and saw that the partialSheet does not fit in the right position. Is there a way to fix it?

![partialsheet_inside_list_view](https://user-images.githubusercontent.com/55566346/80445545-c4be3980-893e-11ea-8e3e-020a32ec323d.gif)

**Comment by AndreaMiotto** [comment]
Are you triggering the partial sheet with the row list? If yes did you put the partial sheet code in the cell list? Did you try to put it outside?

**Comment by phuhuynh2411** [comment]
> Are you triggering the partial sheet with the row list? If yes did you put the partial sheet code in the cell list? Did you try to put it outside?

I think I put it in the row list. You can see the code snippet below.

struct IssueDetailView: View {
    @EnvironmentObject var modelView: IssueDetailModel
    @ObservedObject var issue: Issue
    
    var body: some View {
        List {
            StatusButtonView(issue: self.issue)
        }
    }
}

struct StatusButtonView: View {
    @ObservedObject var issue: Issue
    
    var body: some View {
        Button(action: {
            
        }) {
            Text("View")
        }
        .partialSheet(presented: <#T##Binding<Bool>#>, view: <#T##() -> View#>)
    }
}

**Comment by phuhuynh2411** [comment]
I put the partial sheet outside of the List. It is working properly now.
