### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by vinothvino42** [AndreaMiotto/PartialSheet#2]
Can you please update the package ?

**Comment by AndreaMiotto** [comment]
I will fix it this night, stray tuned!

**Comment by AndreaMiotto** [comment]
I've just tested with Xcode 11.2.1 and everything works well. From swift 5.1 there is the ABI stability it is not needed to recompile the sources.

Can you try the package with a brand new project created with Xcode 11.2.1?

**Comment by vinothvino42** [comment]
I don't how it's working now. Anyway xcode build it successfully.
