### ISSUE TITLE
Enhancement: is it possible to put the partial sheet on the top of the Tab View?

### ISSUE THREAD

**Issue by phuhuynh2411** [AndreaMiotto/PartialSheet#20]
The partial sheet looks great. I was wondering whether it is possible to put it on the top of the Tab View. The built-in sheet is covering the Tab View when opening.

<img width="349" alt="The partial sheet on the top of the Tab View" src="https://user-images.githubusercontent.com/55566346/80552996-7f5b4400-89f2-11ea-8a0e-249a33a547dc.png">

**Comment by AndreaMiotto** [comment]
I've just released the version 2.0 with a lot of breaking changes and it will allow you to do what you are looking for.
And now you can also call it from inside the list items.

**Comment by phuhuynh2411** [comment]
That's great. I cannot test it out because it seems the Swift Package requires the version number in 2.0.0 format instead of 2.0. Can you fix it?

**Comment by AndreaMiotto** [comment]
Fixed, my bad sorry. Try now.
There are a lot of breaking changes so probably you will need to change your code.

**Comment by phuhuynh2411** [comment]
Thanks. Although it requires two more steps to use the partial sheet (one step in version 1), it meets the desired requirement.

By the way, is is possible to add a view to the Partial Sheet top bar? It's something like you can add the Leading View or Trailing View to the NavigationView. I read through your guide on the github, but could not find it.

<img width="346" alt="Screen Shot 2020-04-29 at 09 02 20" src="https://user-images.githubusercontent.com/55566346/80554703-31e1d580-89f8-11ea-8154-ecade7c8f01c.png">

**Comment by AndreaMiotto** [comment]
For sure we can add an enhancement, what kind of view where you thinking about?

**Comment by phuhuynh2411** [comment]
Any view. I would like to add the Remove button on the left and Save button on the right. Ideally, using the data picker inside the partial sheet where we have an ability to select or remove the date.

**Comment by AndreaMiotto** [comment]
Ok, please open a new issue with that request, I will implement as soon as possible, or feel free to start a new Pull Request.
