### ISSUE TITLE
Blur along with opacity

### ISSUE THREAD

**Issue by Cyclic** [AndreaMiotto/PartialSheet#21]
It would be great to have a style that simply takes a bool parameter for blur to produce the effect shown here:
https://medium.com/@edwurtle/blur-effect-inside-swiftui-a2e12e61e750

**Comment by AndreaMiotto** [comment]
Added this option with the version 2.1.0, in the **PartialSheetStyle init** you can now set a `UIBlurEffect.Style`.

**Comment by Cyclic** [comment]
The blur looks great, but I meant the blur effect like you see in the half sheet or partial sheet on the Apple Maps. The background of the partial sheet is blurred for whatever it covers. However, the blur over the main content is great to have as well.
