### ISSUE TITLE
Blur effect on sheet

### ISSUE THREAD

**Issue by Cyclic** [AndreaMiotto/PartialSheet#26]
It would be nice to have a blur effect on the sheet as well, similar to the sheet on Apple Maps.
![9B3C2220-F95A-4B7E-9567-74A1295CF314](https://user-images.githubusercontent.com/553800/80855898-0af2f180-8bfa-11ea-89d7-43445f58fb83.jpeg)

![08EAB340-ADE7-473C-9795-E8465808928F](https://user-images.githubusercontent.com/553800/80855909-2100b200-8bfa-11ea-915b-a38e8245a201.png)

**Comment by AndreaMiotto** [comment]
Yes, yesterday I've tried to implement it, I will release a new version with this between today e tomorrow.

**Comment by styrken** [comment]
@AndreaMiotto, did you ever get around doing this? :-)

**Comment by styrken** [comment]
I have added the feature in #56, please take a look and give me your thoughts :-)
