### ISSUE TITLE
Remove PartialSheet from its view hierarchy when not presented

### ISSUE THREAD

**Issue by Jinya** [AndreaMiotto/PartialSheet#27]
Any possible to using AnyTransiton to insert it into View Hierarchy when presented and remove it when not presented. 
Now partialSheet view is just being hidden off of the screen instead of being removed.
Possible improvements may be like below:
```swift
if presented {
    PartialSheetContent.offset(offsetWhenPresented)
        .transition(anyTransitionMethod).animation(anyAnimation)
} 
else {
    EmptyView()
}
```

**Comment by bernhardwaidacher** [comment]
Any news on this? Or info on how/where to do this?

**Comment by AndreaMiotto** [comment]
This could be an interesting update. But it means refactor the whole modifier and use the Transitions. 
Right now the effort does not justify the improvements, but feel free to implement a PR for this, I may help you.
