### ISSUE TITLE
Static Heights

### ISSUE THREAD

**Issue by halilyuce** [AndreaMiotto/PartialSheet#28]
Hello mate, firstly thanks for this repo :)

I want to use it with custom static heights. 
For example y:200 and y:600 cases. Is there any way to do it ? 

I made this custom modal but it's not working so well. This screenshots will help you to understand what I'm trying to do.

Thanks in advance :)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-05 at 01 50 05](https://user-images.githubusercontent.com/29376592/81021040-e2296100-8e72-11ea-9262-8675d7547ea6.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-05 at 01 50 09](https://user-images.githubusercontent.com/29376592/81021074-f79e8b00-8e72-11ea-9490-ff9f090148d9.png)

**Comment by styrken** [comment]
Hi,

Please provide sample code or project and reopen the issue, thank you.
