### ISSUE TITLE
Sheet is still going upto the top

### ISSUE THREAD

**Issue by anuranBarman** [AndreaMiotto/PartialSheet#3]
Hi, I added this package to make half modals as you mentioned in your stackoverflow answer. But seems like sheet is still going upto the top. The options you can specify while creating the partial sheet does not take any boolean value for it or am I doing wrong? My code is below:

```swift
import SwiftUI
import Combine
import PartialSheet

struct FriendsListView: View {
    
    @ObservedObject var friendListVM:FriendListViewModel = FriendListViewModel()
    @State var showModal:Bool = false
    
    private func addFriend(){
        self.showModal = true
    }
    
    var body: some View {
        NavigationView {
            List {
                ForEach(self.friendListVM.friends) { friendVM in
                    NavigationLink(destination: FriendsDetailView(friendVM: friendVM)) {
                        HStack {
                            Image(friendVM.profilePicture)
                                .resizable()
                                .frame(width:50,height:50)
                            VStack(alignment:.leading) {
                                Text(friendVM.name)
                                .font(.title)
                                Text("$ 10.00")
                            }
                        }
                    }
                }
            }
        .navigationBarTitle("Friends")
            .navigationBarItems(trailing: Button(action:self.addFriend){
                  Image(systemName: "plus")
            })
            
        }.partialSheet(presented: self.$showModal) {
            AddFriendView(isPresented: self.$showModal)
        }
        
        
    }
}

struct FriendsListView_Previews: PreviewProvider {
    static var previews: some View {
        FriendsListView()
    }
}
```

The View is looking like below in simulator for iPhone 11 Pro Max

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-27 at 00 26 41](https://user-images.githubusercontent.com/22582912/73140163-b8a2b180-409b-11ea-9868-d6ddb2cc4624.png)

**Comment by Dylawelt** [comment]
It would appear you still have your `AddFriendView` acting as a standard SwiftUI modal inside of the partialsheet modal, which would explain why it seems like it’s going to the top, but not all the way. Remove `isPresented: self.$showModal ` from `AddFriendView`, and partialSheet should work as intended  (you didn’t provide the code for the AddFriendView, but I’m assuming you’re using a normal view acting as a modal). Hope this helps!

**Comment by AndreaMiotto** [comment]
> Hi, I added this package to make half modals as you mentioned in your stackoverflow answer. But seems like sheet is still going upto the top. The options you can specify while creating the partial sheet does not take any boolean value for it or am I doing wrong? My code is below:
> 
> ```swift
> import SwiftUI
> import Combine
> import PartialSheet
> 
> struct FriendsListView: View {
>     
>     @ObservedObject var friendListVM:FriendListViewModel = FriendListViewModel()
>     @State var showModal:Bool = false
>     
>     private func addFriend(){
>         self.showModal = true
>     }
>     
>     var body: some View {
>         NavigationView {
>             List {
>                 ForEach(self.friendListVM.friends) { friendVM in
>                     NavigationLink(destination: FriendsDetailView(friendVM: friendVM)) {
>                         HStack {
>                             Image(friendVM.profilePicture)
>                                 .resizable()
>                                 .frame(width:50,height:50)
>                             VStack(alignment:.leading) {
>                                 Text(friendVM.name)
>                                 .font(.title)
>                                 Text("$ 10.00")
>                             }
>                         }
>                     }
>                 }
>             }
>         .navigationBarTitle("Friends")
>             .navigationBarItems(trailing: Button(action:self.addFriend){
>                   Image(systemName: "plus")
>             })
>             
>         }.partialSheet(presented: self.$showModal) {
>             AddFriendView(isPresented: self.$showModal)
>         }
>         
>         
>     }
> }
> 
> struct FriendsListView_Previews: PreviewProvider {
>     static var previews: some View {
>         FriendsListView()
>     }
> }
> ```
> 
> The View is looking like below in simulator for iPhone 11 Pro Max
> 
> ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-27 at 00 26 41](https://user-images.githubusercontent.com/22582912/73140163-b8a2b180-409b-11ea-9868-d6ddb2cc4624.png)

I cannot reproduce your problem if you don't provide me the full code.
Remember that the Partial sheets extends as the size of the child view

**Comment by maxakash** [comment]
I am also facing the same issue. I also tried copying your view that is displaying a toggle button but still the sheet is going to the top.
Please help me.
