### ISSUE TITLE
Keyboard appearance bug

### ISSUE THREAD

**Issue by RobertKoval** [AndreaMiotto/PartialSheet#31]
Keyboard overlaps TextField/UISearchBar

![IMG_2643](https://user-images.githubusercontent.com/22445842/82018804-b0907100-968e-11ea-9920-fe7b9a618192.jpg)
![IMG_2642](https://user-images.githubusercontent.com/22445842/82018809-b25a3480-968e-11ea-90a2-463327accc50.jpg)

**Comment by AndreaMiotto** [comment]
fixed in 2.1.4
