### ISSUE TITLE
Drag to take full screen

### ISSUE THREAD

**Issue by sethi-ishmeet** [AndreaMiotto/PartialSheet#33]
Thanks for the amazing Swift package. It saved a lot of hours of work. 

I would like to ask if it's possible to implement a functionality where, the partial sheet should have the max height equal to half the screen size (or height passed in configuration) on initial load and when swipe up, the height should change to full screen. I understand this should only be possible for contents which are of size more than half of screen.

Something like this gif. Where the partial screen takes full height when searching using a keyboard. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17765279/82155018-983b7480-988f-11ea-8b92-301bebafde1e.gif)

**Comment by styrken** [comment]
I am closing this issue as it is not planned as a feature at the moment.
