### ISSUE TITLE
No way to initialise PartialSheet using binding starting 2.0

### ISSUE THREAD

**Issue by NeverwinterMoon** [AndreaMiotto/PartialSheet#34]
I have looked at the library before, but have never used it. Now I've decided to use it and, as I understand, starting from 2.0, it's not possible to initialise PartialSheet using a binding, and is possible only using a user action (pressing a button and calling the sheet action there). If this is indeed so, I think it's a bit of a downgrade and is not in line with the SwiftUI approach.

I use global state for my navigation, so before, I could configure the state (in case of deep linking, for instance) and this way navigate to any of the views, including an opened sheet. Now it looks like I can't do that.

**Comment by WebMajstr-** [comment]
I have the same issue :(

**Comment by Danny-SS** [comment]
Same... I've had to use some combine and receive blocks to activate sheet based on other state changes.  Not a concise as using a binding.

**Comment by AndreaMiotto** [comment]
In the PartialSheet Manager there is a Published property `isPresented` you can use it as a Binding property, isn't it?

**Comment by NeverwinterMoon** [comment]
It’s not exactly the same. As I’ve mentioned, I use a global application state. And I have routing state properties there. I pass these state properties as bindings for presented views. That’s what I am using to present any views, be it through a NavigationLink or a sheet or whatever.

**Comment by AndreaMiotto** [comment]
I see, feel free to open a PR, until the 12th of this month I do not have time to try to find an alternative solution.
I would like your help.

Thank you.

**Comment by styrken** [comment]
Not 100% sure I get what you mean. Are you thinking of the same interface as `.alert(isPresented: self.$showAlert)` has?

**Comment by AndreaMiotto** [comment]
yes, that's what he was looking to have

**Comment by woko666** [comment]
I've opened a PR (#67)
