### ISSUE TITLE
Compatibility issue with SwiftUIX Search-bar

### ISSUE THREAD

**Issue by satan87** [AndreaMiotto/PartialSheet#36]
Hello,

I'm using 2 Swift package for my SearchBar (SWIFTUIX), and Modal (PARTIALSHEET).

When I use the search bar, the keyboard appears and the view is above the keyboard.

Before
<img width="431" alt="Screen Shot 2020-05-22 at 1 22 30 PM" src="https://user-images.githubusercontent.com/5104971/82693290-4b5cf280-9c2f-11ea-8a89-e9704cd263ac.png">

When I add .addPartialSheet(style: .defaultStyle())
<img width="439" alt="Screen Shot 2020-05-22 at 1 23 05 PM" src="https://user-images.githubusercontent.com/5104971/82693342-60398600-9c2f-11ea-9589-a234e7a4875b.png">
This might be related to issue #35

**Comment by AndreaMiotto** [comment]
Should be fixed, give it a try with v2.1.6
