### ISSUE TITLE
onDismiss not being called from closePartialSheet

### ISSUE THREAD

**Issue by Danny-SS** [AndreaMiotto/PartialSheet#38]
It is documented to run the onDismiss, but does not.

```    
/// Close the Partial Sheet and run the onDismiss function if it has been previously specified

    public func closePartialSheet() {
        self.isPresented = false
    }
```

The onDismiss function is run when dragging to close as expected.

I added something like this and bound it to an action and now I get the onDismiss to fire.

```
public func dismissPartialSheet() {
        self.isPresented = false
        self.onDismiss?()
}
```

I am not sure if there was intent to have the closePartialSheet merely close the sheet (e.g. maybe a cancel-type scenario) without running the onDismiss function.

**Comment by AndreaMiotto** [comment]
Fixed with 2.1.5, thank you for your feedback
