### ISSUE TITLE
Don't work on iOS 13.1

### ISSUE THREAD

**Issue by ViktoriaRohozhyna** [AndreaMiotto/PartialSheet#40]
sheet don't work on devices with iOS 13.1 or 13.0
it shows only white screen

**Comment by AndreaMiotto** [comment]
Swift UI keeps evolving in every version of iOS, and soon it will probably release very big changes. You should use always the latest version of iOS until SwiftUI is more stable, probably with iOS 14.

And I cannot add the minimum requirements iOS version as 13.2 as the swift package manager allows only integers like this:

```
platforms: [
        .iOS(.v13)
	],
```
