### ISSUE TITLE
Animation bugs with pickers

### ISSUE THREAD

**Issue by AlanJinqs** [AndreaMiotto/PartialSheet#43]
Hi there, thanks for the great library! I really love to use this in my project but I just found some strange animation when using the DatePicker or Picker inside the sheet. This is the screen rec, you can see the sheet is moving up and down while using the DatePicker
![](https://i.ibb.co/C1yyw7S/rec2.gif)
And the code is basically this
```swift
                    .onTapGesture {
                        self.partialSheetManager.showPartialSheet({
                            print("Partial sheet dismissed")
                        }) {
                            VStack() {
                                Text("Some Title").bold().font(.title)
                                DatePicker("Please select a date", selection: self.$selectedDate, in: ...Date(), displayedComponents: .date).labelsHidden()
                            }.frame(height: 300)
                        }
                    }
```
Is there any way to fix this? Thx a lot

**Comment by SlayterDev** [comment]
Experiencing this as well and other issues in #44

**Comment by schwjustin** [comment]
Experiencing this issue when using a WheelPickerStyle Picker

**Comment by styrken** [comment]
I cannot reproduce this issue on iOS 14 beta 4. Can you give some more details?
