### ISSUE TITLE
Picker in partial sheet causes issues

### ISSUE THREAD

**Issue by SlayterDev** [AndreaMiotto/PartialSheet#44]
So I've noticed placing a picker in a partial sheet causes some weird issues.

1. Dragging on the picker triggers the drag gesture of the sheet. So when you try to drag on the picker the sheet moves a bit before the picker does its thing.
2. Related to 1, if you have a TextField AND a picker in the partial sheet things get really bumpy. If the keyboard is open and you drag the picker, the drag gesture of the sheet gets triggered (as mentioned above) which tells the keyboard to dismiss. SwiftUI can't seem to handle this all at once and crashes.

**Crash message**

```
AttributeGraph precondition failure: setting value during update: 75004.
2020-06-29 09:14:19.822339-0500 Fox Relay[13433:3310197] [error] precondition failure: setting value during update: 75004
```

The crash originates [here](https://github.com/AndreaMiotto/PartialSheet/blob/9b905dcaeedb96d8c1793de945489ed76df6754f/Sources/PartialSheet/PartialSheetViewModifier.swift#L296) and is triggered  [here](https://github.com/AndreaMiotto/PartialSheet/blob/9b905dcaeedb96d8c1793de945489ed76df6754f/Sources/PartialSheet/PartialSheetViewModifier.swift#L223)

I like this library and would like to continue using it for my app so some guidance on this would be appreciated.

**Comment by secretmode** [comment]
Even within the example code (the one with a textfield), when you highlight the textfield then drag the partial sheet it crashes with a similar crash message like SlayterDev provided.

**Comment by SlayterDev** [comment]
Bumping this thread. Would love to get a response on this.

Probably going to have to fork this and rip out some functionality as it stands.

**Comment by styrken** [comment]
Hi, we have just merged a fix to master that fixes the crash when keyboard is dismissed.

**Comment by styrken** [comment]
Just added a PR that fixes the picker issue
