### ISSUE TITLE
Rest all ObservedObjects inside navigatoinview childs in tabbar

### ISSUE THREAD

**Issue by ahs441** [AndreaMiotto/PartialSheet#46]
if we place a TabVIew and add a partial sheet to it, then add some NavigationViews for tabs and go to inside of NavigationView child views if view uses ObservedObject for ViewModel when we open partial sheet all variables in ObservedObject of ViewModel was reset

**Comment by styrken** [comment]
Hi,

Please provide sample code or project and reopen the issue, thank you.
