### ISSUE TITLE
Doesn't work on macOS as advertised

### ISSUE THREAD

**Issue by fordee** [AndreaMiotto/PartialSheet#47]
I tried this in a Mac app and found that it is full of UIKit code. If you are intending it for Mac Catalyst apps only, then update the README to say macOS Catalyst, not macOS.

**Comment by AndreaMiotto** [comment]
What do you mean? it's not mack catalyst, it's SwiftUI.. On which version of mac os are you trying?

**Comment by styrken** [comment]
I think the issue is that the current implementation references UIKit at different places, for example `UIScreen.main.bounds.width`. To fix this we need to abstract it away and introduce `#if os(iOS) ... #else .. #endif`
