### ISSUE TITLE
PartialSheet crashes when trying to dismiss TextField

### ISSUE THREAD

**Issue by mergesort** [AndreaMiotto/PartialSheet#49]
The line `self.dismissKeyboard()` in the code below crashes when dismissing the PartialSheet via a drag gesture if a `TextField` in the PartialSheet has a keyboard presenting. I haven't looked too deeply into this, but I believe this may be because `UIApplication.shared.sendAction(resign, to: nil, from: nil, for: nil)` is calling into something UIKit-related that SwiftUI isn't.

```swift
private func dragGesture() -> _EndedGesture<GestureStateGesture<DragGesture, DragState>> {
    DragGesture()
        .updating($dragState) { drag, state, _ in
            self.dismissKeyboard()
            let yOffset = drag.translation.height
            let threshold = CGFloat(-50)
            let stiffness = CGFloat(0.3)
            if yOffset > threshold {
                state = .dragging(translation: drag.translation)
            } else if
                // if above threshold and belove ScreenHeight make it elastic
                -yOffset + self.sheetContentRect.height <
                    UIScreen.main.bounds.height + self.handlerSectionHeight
            {
                let distance = yOffset - threshold
                let translationHeight = threshold + (distance * stiffness)
                state = .dragging(translation: CGSize(width: drag.translation.width, height: translationHeight))
            }
    }
    .onEnded(onDragEnded)
}
```

This should be reproducible in a pretty simple use case, but if not let me know and I can try to isolate a sample case.

Thanks a lot!

**Comment by Nosrac** [comment]
FYI, you can use this pull request until it's merged into master: https://github.com/AndreaMiotto/PartialSheet/pull/48
