### ISSUE TITLE
Keybord makes the view top offset too much

### ISSUE THREAD

**Issue by golangnext** [AndreaMiotto/PartialSheet#53]
As titled :)  

This video is taken from the builtin example

![top](https://user-images.githubusercontent.com/47587402/90225857-6bc6d280-de55-11ea-985c-31f4b32fb782.gif)

**Comment by styrken** [comment]
I got the same issue and is looking into a fix

**Comment by styrken** [comment]
Problem seems to only happen for keyboards that has suggestions enabled

**Comment by styrken** [comment]
The code has been merged to master. A new release is planned for next week.

**Comment by cikpis** [comment]
Hey guys, I'm still having this issue. Check the attached video. Any clue?

https://user-images.githubusercontent.com/895478/144199575-7280a7c3-677f-4033-83fb-e38fe9bc5b08.mov
