### ISSUE TITLE
'PartialSheetStyle' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by 1337domz** [AndreaMiotto/PartialSheet#61]
I'm getting this error when I try and create a custom style. This is after adding PartialSheet using SPM.

I _think_ it's because the PartialSheetStyle Struct needs a public init so it can be called when added as a module?

**Comment by miczec** [comment]
same here, any help would be greatly appreciated.

**Comment by 1337domz** [comment]
A temporary solution would be to add the files manually to your project instead of using SPM

**Comment by styrken** [comment]
Just not sure why the compiler does not make it. Anyway, there is a release coming up shortly with the init added

**Comment by styrken** [comment]
Hello, a new release has been made
