### ISSUE TITLE
Xcode 12 canvas

### ISSUE THREAD

**Issue by miczec** [AndreaMiotto/PartialSheet#62]
Xcode 12 canvas crashes as soon as PartialSheet is imported to view. Any idea how to fix this?

**Comment by styrken** [comment]
I will download the latest Xcode and have a look

**Comment by miczec** [comment]
Thank you! I have to correct myself - it only crashes when .addPartialSheet() is added.

**Comment by serbats** [comment]
It also crashes on Xcode 11.6
Commenting .addPartialSheet() fixes preview crash

**Comment by styrken** [comment]
well I think there is generally something wrong in the newest Xcode version with the partial sheet. It does not behave as expected

**Comment by styrken** [comment]
I can't seem to reproduce: Is it possible for you to give me an example project?

**Comment by serbats** [comment]
This no more reproduces in XCode 12.
Seems like Apple fixed something in Xcode

**Comment by styrken** [comment]
Awesome. Thank you for confirming that it has been resolved.
