### ISSUE TITLE
Button is not working inside ScrollView

### ISSUE THREAD

**Issue by hyder50** [AndreaMiotto/PartialSheet#65]
I have content for SheetView inside a ScrollView. And under ScrollView there are few UI elements and one button. So when the view loaded the first time the button is not working. But after doing the scroll event the button starts working. Here is my code,

//Main ContentView
`var body: some View {

        HStack {
            Spacer()
            Button(action: {
                self.partialSheetManager.showPartialSheet({
                     print("normal sheet dismissed")
                }) {
                     SheetView()
                }
            }, label: {
                Text("Display the Partial Sheet")
            })
        }
    }`

//SheetView

`struct SheetView: View {
    var body: some View {
        VStack {
            
            ScrollView {
                Text("Hello")
                
                Button(action: {
                    print("Button is tapping")
                }) {
                    Text("Tap Here")
                }
            }
        }
    }
}`

**Comment by Reedyuk** [comment]
I'm getting something similar, When i press the button before scrolling:
![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 11 30 10](https://user-images.githubusercontent.com/3853006/91711182-61a71280-eb7d-11ea-8c01-803a8bc29237.png)

And then when i scroll and press the button(expected display for the first scenario):
![Simulator Screen Shot - iPhone 11 - 2020-08-31 at 11 30 16](https://user-images.githubusercontent.com/3853006/91711197-69ff4d80-eb7d-11ea-9ad3-31577fd34995.png)

**Comment by styrken** [comment]
Hi. Is it iOS13 or 14?

**Comment by Reedyuk** [comment]
14

**Comment by hyder50** [comment]
The issue exists in iOS 13 but not sure on iOS 14

**Comment by styrken** [comment]
Does scrollview try to take up the full spage of the frame? Might help by setting an explicit framesize for the scrollview.

**Comment by hyder50** [comment]
One update on this issue. When i used UIButton by using UIViewRepresentable

**Comment by LuboZ** [comment]
Any news ? Got same error using List view

**Comment by styrken** [comment]
Sorry, there is no news yet on this issue.

**Comment by rushairer** [comment]
I have the same problem.

**Comment by bbongrip** [comment]
I had this problem as well and solved it by adding the modifier .highPriorityGesture() to the ScrollView and passing in the drag gesture from the sheet view. Hope this helps

**Comment by rushairer** [comment]
@bbongrip Could you pull your merge?

**Comment by bbongrip** [comment]
@rushairer no need to a pull.  You just would add .highPriorityGesture() modifier to your Scrollview that your adding to the content of the partialSheet. Then get the dragGesture of the partialSheet and pass that to .highpriorityGesture($dragGesture)

**Comment by styrken** [comment]
maybe we should update the documentation with this

**Comment by rushairer** [comment]
@bbongrip  Thanks.

**Comment by d4rkd3v1l** [comment]
@bbongrip How do I actually pass in the drag gesture from the partial sheet? You just have a @State property, but where does this get updated/set?

**Comment by bbongrip** [comment]
@d4rkd3v1l I ended up making the drag gesture an @Published property so I could access it anywhere. But I suppose in my sample code above it should be an @Binding property. The drag gesture gets set and comes from the Partial sheets implementation of is own dragging motions. Just simply create a binding for that drag gesture or some other observed property wrapper.

**Comment by styrken** [comment]
A PR with updated documentation would be appreciated

**Comment by styrken** [comment]
@bbongrip would you be able to share your code? Thanks in advance 🥇

**Comment by styrken** [comment]
I have looked a bit more into it and it is indeed the dragGesture that takes over the whole view. In some cases it can be fixed by just adding an onTapGesture {} to your view/button/picker but this does not work the DatePicker - then buttons stops to work.

We need to find a way for having the priority of the drag gesture lowered

**Comment by jfredsilva** [comment]
I also had this issue on a TextField. It was also solved by adding onTapGesture {} on it

**Comment by AndreaMiotto** [comment]
Check version 3.0 and if you still have the issue, feel free to reopen the issue

**Comment by liangwangcm** [comment]
> I also had this issue on a TextField. It was also solved by adding onTapGesture {} on it

just curious why this solution works?
