### ISSUE TITLE
'isPresented' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by dreeye** [AndreaMiotto/PartialSheet#68]
Hello,
I installed it through SPM and then tried PushNavigationExample and an error was reported.

`'isPresented' is inaccessible due to 'internal' protection level`

**Comment by styrken** [comment]
iOS 14?

**Comment by dreeye** [comment]
No, IOS 13.0. The version of XCODE is 11.7

**Comment by styrken** [comment]
Does this happen in the example project? I have just tried in the example project and also used a separate project where I included the lib via swift package manager and had no trouble.

Can you provide your project?

**Comment by styrken** [comment]
Closed due to inactivity.
