### ISSUE TITLE
Not working fine with NavigationView & NavigationLink

### ISSUE THREAD

**Issue by wailbabou** [AndreaMiotto/PartialSheet#7]
I have the use case below : 

- NavigationView with a NavigationLink (send the user to second view[page])
- the second view use .partialSheet 
- the partialSheet view has a Textfield
when the keyboard is opened , there is an issue as the image below : 

![84661094_887988474971084_2607907784263467008_n](https://user-images.githubusercontent.com/17969012/74395198-fe3ada80-4e0e-11ea-9ff6-e78addfef935.jpg)
____________
![85054519_210616900083226_3467720100453285888_n](https://user-images.githubusercontent.com/17969012/74395202-ff6c0780-4e0e-11ea-98f2-3a81bd3abb0b.jpg)

**Comment by AndreaMiotto** [comment]
I'll give it a look this weekend, thanks for your feedback!

**Comment by AndreaMiotto** [comment]
This is a normal behavior. This component it's just a that wraps your view inside a ZStack with the sheet view, it is not a modal view presented upon the views stack. You should use the .partialSheetModifier just from outside the navigation stack.
You could use the Notification Center to prompt the partial sheet in you root navigation view from any point of you stack.
