### ISSUE TITLE
Thread 1: Fatal error: No ObservableObject of type PartialSheetManager found. A View.environmentObject(_:) for PartialSheetManager may be missing as an ancestor of this view.

### ISSUE THREAD

**Issue by haoyang0517** [AndreaMiotto/PartialSheet#72]
I tried to use the partialSheet in the fullScreenCover. After I used the partialSheet and dismissed the full screen cover. It return this error. Any method that can solved this issue?

```
Thread 1: Fatal error: No ObservableObject of type PartialSheetManager found. A View.environmentObject(_:) for PartialSheetManager may be missing as an ancestor of this view.
```

**Comment by msteini82** [comment]
It's funny, I ran into the same error yesterday. But I just found out it's not a problem within the partial sheet, it's caused by the fullscreenCover, that seems to use it's on environment. To fix the problem you have to passthrough the environmentObject to your fullscreenCoverView like this:

```Swift
struct ContentView: View {

    @EnvironmentObject var partialSheetManager: PartialSheetManager
    @State var showFullScreen = false

    var body: some View {

        Button(action: {
            self.showFullScreen = true
        }) {
            Text("click me")
        }
        .fullScreenCover(isPresented: $showFullScreen) {
            YourAwesomeView().environmentObject(partialSheetManager)
        }

    }

}
```

**Comment by skywalkerlw** [comment]
i got the same problem here and not sure how to fix it

![image](https://user-images.githubusercontent.com/2090084/119498551-17b82980-bda9-11eb-81fe-48b630abde23.png)
