### ISSUE TITLE
DatePicker not rendering well in PartialSheet

### ISSUE THREAD

**Issue by jerryOkafor** [AndreaMiotto/PartialSheet#73]
![IMG_4912](https://user-images.githubusercontent.com/12306753/94990057-08ae0e00-0571-11eb-9161-6174dd9d1223.PNG)![IMG_4913](https://user-images.githubusercontent.com/12306753/94990060-0e0b5880-0571-11eb-9541-ecf6f0dc366b.PNG)

I observed that when a `DatePicker` is added to `PartialSheet` it does not render well until a date is selected.

**Comment by matepapp** [comment]
Happened to me as well. Have you found any workaround or solution @jerryOkafor?

**Comment by styrken** [comment]
On master it seems to render just fine but I am not able to select dates. Currently lookin into the drag gesture as it is the trouble-maker!

![Simulator Screen Shot - iPhone 12 - 2021-02-06 at 23 17 29](https://user-images.githubusercontent.com/2223435/107130805-7d9fa480-68d1-11eb-83f2-bb32f08ac88c.png)

**Comment by AndreaMiotto** [comment]
Check version 3.0 and if you still have the issue, feel free to reopen the issue
