### ISSUE TITLE
Sometime crash in value.append(contentsOf: nextValue())

### ISSUE THREAD

**Issue by linsyorozuya** [AndreaMiotto/PartialSheet#75]
[7767:1457502] [error] precondition failure: invalid value type for attribute: 2518736 (saw PreferenceList, expected Array<PreferenceData>)
AttributeGraph precondition failure: invalid value type for attribute: 2518736 (saw PreferenceList, expected Array<PreferenceData>).
AttributeGraph precondition failure: invalid value type for attribute: 2518736 (saw PreferenceList, expected Array<PreferenceData>).

**Comment by styrken** [comment]
Please provide more info and context
