### ISSUE TITLE
can not work with ZStack

### ISSUE THREAD

**Issue by Jaschenn** [AndreaMiotto/PartialSheet#8]
Thanks a lot to your project! but when I put my partialSheet on a button which is in a ZStack, and set the alignment .bottomTrailing, but it doesn't work .

the code as follows:
```swift
ZStack(alignment: .bottomTrailing){
            VStack{
                Picker("helo",selection: $selectedOption){
                    Text("People").tag(0)
                    Text("Tags").tag(1)
                }.pickerStyle(SegmentedPickerStyle())
                
                List{
                    ForEach(tags, id: \.self){
                        tag in
                        Text(tag.name ?? "")
                        
                    }
                }
            }.blur(radius: addMaterialMode==false ? 0: 1000)
            
            Button(action:{
                self.addMaterialMode = true
            }){
                Image(systemName: "plus.circle.fill").resizable().frame(width: 70,height: 70).padding()
            }.partialSheet(presented: $addMaterialMode) {
                Text("hello")
            }
        }
```
it shows like this:

<img width="193" alt="截屏2020-02-27下午1 09 47" src="https://user-images.githubusercontent.com/27953082/75414124-70a8d000-5962-11ea-9ab2-7d3ca58a8bb0.png">

I have tried ```.bottomTrailing``` ```.top```... but all of those don't work properly
, it can only show in the center of the screen

**Comment by AndreaMiotto** [comment]
try to put the 

.partialSheet() on the ZStack, or just provide me the full testable code please
