### ISSUE TITLE
Drag is not instantaneous

### ISSUE THREAD

**Issue by schwjustin** [AndreaMiotto/PartialSheet#81]
I recommend changing the default DragGesture minimumDistance from 30 to 0 to make dragging the PartialSheet instantaneous and therefore more fluid. `DragGesture(minimumDistance: 0, coordinateSpace: .local)`

**Comment by styrken** [comment]
Yeah that makes sense - not sure why it was 30. I think it had something to do with some conflict when dragging date pickers

**Comment by styrken** [comment]
I have just tested it with minimumDistance: 0 and it works nicely but when having pickers inside the view, the drag gesture seems to override the pickers scroll gesture and then you cannot use pickers. 

I understand the magic ```30``` is not really a bug fix.

**Comment by styrken** [comment]
For whatever reason it seems to work when you register an onTapGesture on the picker itself.

```
struct PickerSheetView: View {
    var strengths = ["Mild", "Medium", "Mature"]
    @State private var selectedStrength = 0

    var body: some View {
        VStack {
            VStack {
                Text("Settings Panel").font(.headline)
                Picker(selection: $selectedStrength, label: EmptyView()) {
                    ForEach(0 ..< strengths.count) {
                        Text(self.strengths[$0])
                    }
                }.onTapGesture {
                    // Fixes issue with scroll
                }
            }
            .padding()
            .frame(height: 250)
        }
    }
}
```
