### ISSUE TITLE
closePartialSheet() withAnimation

### ISSUE THREAD

**Issue by ArturoLee** [AndreaMiotto/PartialSheet#87]
When I call closePartialSheet(), it doesn't close with animation like when you tap on the Cover view.

I tried changing the function like this but it didn't work:
```
public func closePartialSheet() {
        withAnimation {
            self.isPresented = false
        }
        self.onDismiss?()
}
```

Any thoughts on how I could fix this? Thanks!

**Comment by jfrodden** [comment]
I too would like to programmatically initiate the dismiss animation.

**Comment by ArturoLee** [comment]
@jfrodden 
I got it to animate when it closes. However, the downside is that the content view goes empty right before the animation starts. I figure it better than having no animation though. But still, I wish there was a way to keep the content view while it is animating out.

```
@Published var isPresented: Bool = false {
        didSet {
            if !isPresented {
                self.content = AnyView(EmptyView())
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) { [weak self] in
                    self?.onDismiss = nil
                }
            }
        }
    }
```

```
public func closePartialSheet() {
        DispatchQueue.main.async {
            withAnimation {
                self.isPresented = false
            }
        }
        self.onDismiss?()
    }
```

**Comment by ArturoLee** [comment]
@jfrodden 
Okay I figured out how to animate out using a publisher in the PartialSheetManager class.

In the PartialSheetManager class add:
`let closePublisher = PassthroughSubject<Void, Never>()`

Then change the closePartialSheet func to:
`self.closePublisher.send()`

And finally at the end of the ZStack in the iPhoneSheet func in the PartialSheetViewModifier class add:
```
.onReceive(manager.closePublisher, perform: { _ in
                withAnimation {
                    self.manager.isPresented = false
                    self.dismissKeyboard()
                    self.manager.onDismiss?()
                }
        })
```

Only thing I'm not sure about is including the dismissKeyboard call in there. I guess it doesn't hurt. I'lll try to submit a pull request when I can.

**Comment by styrken** [comment]
Hi, please submit a PR

**Comment by juanm4** [comment]
It's dangerous to modify lib files directly because when you update the lib you will miss all of them). 

I have done some tests and I have discovered that if you wrap `partialSheetManager.closePartialSheet()` inside a `withAnimation` tag you can achieve what you want: It closes with the same animation like if you click outside the sheet.

For example: 

```
Button(action: {
    withAnimation {
        partialSheetManager.closePartialSheet()
    }
}, label: {
    Text("Close")
})
```

I hope this helps you!!
