### ISSUE TITLE
`.partialSheet` view modifier does not present the PartialSheet if being called rapidly

### ISSUE THREAD

**Issue by chuymaster** [AndreaMiotto/PartialSheet#89]
First of all, thank you for making such a great library! I would like to report a bug and get any idea of how to fix.

# Issue

When using `.partialSheet` view modifier, if I tap the button to open, then tap outside to close the PartialSheet rapidly, it will not open anymore at some point.

- Video of the behavior (I tapped the button rapidly)

https://user-images.githubusercontent.com/8290104/110073982-bf821480-7dc3-11eb-9819-560ca24ef1e0.mp4

# Code to reproduce

```swift
import PartialSheet
import SwiftUI

@main
struct myApp: App {
    var body: some Scene {
        let contentView = ContentView()
            .environmentObject(PartialSheetManager())

        WindowGroup {
            contentView
        }
    }
}


struct ContentView: View {
    @EnvironmentObject var partialSheetManager: PartialSheetManager
    @State var isPresented: Bool = false

    var body: some View {
        VStack {
            Button(action: {
                isPresented = true
            }, label: {
                Text("Button")
            })
            .padding()
            Spacer()
        }
        .addPartialSheet()
        .partialSheet(isPresented: $isPresented) {
            Text("PartialSheet")
        }
    }
}
```

# Cause

In `PartialSheetViewModifier.swift` I found that both `savedValue` and `value` in `update` function would always become `true` at a certain point. Therefore the PartialSheet view does not get updated and not presented.

```
    // hack around .onChange not being available in iOS13
    class Model {
        private var savedValue: Bool?
        func update(value: Bool) -> Bool {
            print("savedValue: \(savedValue), newValue: \(value)")
            guard value != savedValue else { return false }
            savedValue = value
            return true
        }
    }
````

Log
```
savedValue: nil, newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: false
savedValue: Optional(false), newValue: true
--- From here no matter how many times I press the button, both values are always `true`. ---
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
savedValue: Optional(true), newValue: true
```

# What I tried

I tried changing the `body` of `PartialSheetAddView` struct to observe `isPresented` value with native `.onChange` for iOS 14 but it won't fix.

```
    var body: some View {
        if #available(iOS 14, *) {
            return AnyView(base
                .onChange(of: isPresented) { value in
                DispatchQueue.main.async(execute: updateContent)
            })
        } else {
            if model.update(value: isPresented) {
                DispatchQueue.main.async(execute: updateContent)
            }
            return AnyView(base)
        }
    }
    
```

# Workaround

Presenting PartialSheet with `showPartialSheet()` method seems to work fine.

**Comment by styrken** [comment]
Hi @chuymaster. Would you be willing to submit a fix / PR?

Thank you

**Comment by chuymaster** [comment]
@styrken Hi, unfortunately this is beyond my ability to fix... sorry

**Comment by rsmairat** [comment]
Try setting savedValue to false initially:

  class Model {
        private var savedValue: Bool? = false
        func update(value: Bool) -> Bool {
            guard value != savedValue else { return false }
            savedValue = value
            return true
        }

**Comment by AndreaMiotto** [comment]
Check version 3.0 and if you still have the issue, feel free to reopen the issue.
PSButton helps to avoid rage tapping

**Comment by chuymaster** [comment]
@AndreaMiotto Thank you very much for such a care! Unfortunately our app still supports iOS 14 so we cannot upgrade. But this will should be very helpful to other developers!

**Comment by chuymaster** [comment]
@aimeecesler 

> clicking rapidly you occasionally just get an empty sheet with no content

Yes, I occasionally find that too. But it happens rarely so I ignored this.

**Comment by AndreaMiotto** [comment]
You can easily fork the repo, and remove the Material part than you should be able to support iOS 14.. I didn't have time for that right now, maybe I'll make an update in the next days, or feel free to make a PR to support it.
For the rage click check the PSButton.
