### ISSUE TITLE
need no handleBar option

### ISSUE THREAD

**Issue by jfrodden** [AndreaMiotto/PartialSheet#90]
Plz add ability to have no handleBar and let the top edge of the content be the top edge of the sheet with the corner radius applied to that top edge of the content.

I can approximate this by making the background `.solid(.clear)`, the handleBarColor `.clear`, and using a `RoundedRectangle` for the content, but it'd be nice to have a simple noHandleBar option.

**Comment by styrken** [comment]
Yeah would great. The handlebar could just check if the color is .clear and then remove it self. Please submit a PR.

**Comment by styrken** [comment]
This has just been merged in #100
