### ISSUE TITLE
Enabling dynamic height sizing on iPad?

### ISSUE THREAD

**Issue by NCrusher74** [AndreaMiotto/PartialSheet#91]
I've got an list of options I'm trying to present in a sidebar menu. Each of those views sizes may be different, but it's unlikely any of them are going to have enough content to look good in as a .sheet on iPad.

However, since my app is most likely to be used on iPad or Mac (it's for curating audiobook libraries, and people generally do that sort of thing on platforms with more screen real estate) these views would look a lot better if they were `ActionSheet` size or thereabouts. However, I need more flexibility for the content I'm presenting than an `ActionSheet` allows for.

I'm perfectly willing to do the work required myself, but I'm still really new to SwiftUI and at present the information I'm seeing on dynamically sizing views using `GeometryReader` are going _whoosh_, right over my head.

Would it be trivial to add this sort of functionality into PartialSheet, or is that a harder nut to crack than I'm imagining?

**Comment by styrken** [comment]
Hi @NCrusher74. I'am not sure really. I think the iPad uses a modalsheet instead of the iPhone implementation and that might make it more hard to fix.

**Comment by nikitaame** [comment]
Was this suggestion closed as implemented or as a no go?
