### ISSUE TITLE
Text Field not editable and Switch not working

### ISSUE THREAD

**Issue by nneuberger1** [AndreaMiotto/PartialSheet#92]
I'm seeing an odd behavior on the sample app with the Normal example. I can't edit the Textfield and I can't select the Toggle. I've tested it on a device and several iOS Simulators.  Because I can't select the toggle, the drawer doesn't slide up like the sample video.

It does work fine on the macOS side however. 

I'm using XCode 12.3 on macOS Big Sur with M1.

**Comment by nneuberger1** [comment]
It's working for:
- iPad Pro 4th Gen 14.1 - Sim
- iPad Pro 9.7 - Sim

Not working for:
- iPhone 8 sim
- iPhone SE 2nd gen sim
- iPod Touch 7th gen sim
- iPhone 12 Pro 14.2 - sim


After running the Debug Hierarchy in XCode, I noticed that the iPad version, the sheet is in front of everything.  But on the iOS Sims using the same Debug Hierarchy, the sheet is actually behind the main screen. I'm sure that's why you can do anything on the screen. I'm not sure what the fix is however.

**Comment by nneuberger1** [comment]
![ios-debug](https://user-images.githubusercontent.com/392412/111496575-6ba1f480-870e-11eb-9532-cac1a38c8ec2.png)
![iPad-debug](https://user-images.githubusercontent.com/392412/111496576-6c3a8b00-870e-11eb-9ccf-67088af245c2.png)

**Comment by styrken** [comment]
This might be issue we have with controls not being able to respond in various cases.

**Comment by minwonki** [comment]
I have a similar problem.
In the sample downloaded by master branch, TextField does not work, but in PartialSheet2.1.11 installed with SPM, TextField works normally.

**Comment by Dilan-Anuruddha** [comment]
Not working on Xcode 12.5 Beta 3 also

**Comment by AppleTTT** [comment]
same problem

**Comment by kisjoke91** [comment]
I had the same problem, but is installed it via SPM as mentioned above, and it works now.

**Comment by fluffy919** [comment]
> I have a similar problem.
> In the sample downloaded by master branch, TextField does not work, but in PartialSheet2.1.11 installed with SPM, TextField works normally.

TextField is behind the main view with that branch. It does not work.

**Comment by AndreaMiotto** [comment]
Can you check with the version 2.1.12? it should been fixed

**Comment by fluffy919** [comment]
> Can you check with the version 2.1.12? it should been fixed

Thanks for your comment. I have another issue with PartialSheet. It works randomly. Sometimes it shows the TextField very well, but sometimes it does not show that at all. However, I am sure that the TextField is behind the main view. Do I have to open another issue for this?

**Comment by kisjoke91** [comment]
It works for me, thank you for that 💕.
