### ISSUE TITLE
Unwanted content offset on bottom of sheet.

### ISSUE THREAD

**Issue by ctsmith5** [AndreaMiotto/PartialSheet#93]
Awesome resource thanks for creating! However I'm seeing a wierd issue where the content laid out in the partial sheet is given an automatic and mandatory offset about 60pts from the bottom. If I change the offset of my view to compensate it just shifts down in the sheet and leaves unnecessary space in the top. Anyone know how to disable this when the partial sheet is created?
![Offset Problem](https://user-images.githubusercontent.com/35198533/112860382-c24ded80-9081-11eb-8582-29a65ba8cbd5.png)

**Comment by famictech2000** [comment]
I have the exact same question!? Were you able to resolve?

**Comment by ctsmith5** [comment]
I just know that this is the section where it is being affected in the view modifier and if we could override I think there could be a resolution. 
![image](https://user-images.githubusercontent.com/35198533/112905315-330ffc80-90b8-11eb-97a7-f2b0b7fd9b84.png)

**Comment by jtressle** [comment]
Not sure if this is related, but the example now doesn't have enough spacing for iPhones with front-id cameras.  The touch-ID phones have the correct spacing.  PartialSheet version is 2.1.12.

Thanks
