### ISSUE TITLE
No instructions for App delegate based app

### ISSUE THREAD

**Issue by misbell** [AndreaMiotto/PartialSheet#95]
I start with App delegate, so my SceneDelegate doesn't look anything like you show. AppDelegate with a UITabController and I hang UIHostingControllers off that.

I literally have no idea where to place the code based on your instructions.

What should have taken me minutes is going to take me hours to figure out now.

**Comment by oleiade** [comment]
While I understand your frustration @misbell, keep in mind that this is an open-source project, and that @AndreaMiotto basically works for free here. It might take you hours to figure out how to do it, but @AndreaMiotto doesn't owe you any sorts of instructions, it's just unfortunate he/she didn't find the time to put them together yet ;-)

If you ever figure out though, I'd be glad to check it as I am trying to figure it out myself.

**Comment by misbell** [comment]
Good point

**Comment by kschins** [comment]
@misbell you would need to follow the logic to add a partial sheet to each content view in your UIHostingViewControllers. Although when presenting a partial sheet from the hosting controller, it doesn't cover the UITabBar. I assume this is a limitation of SwiftUI at the moment and not being able to access the entire view hierarchy.
